### PR TITLE
update diagonal QN models

### PR DESCRIPTION
**Pull request by dpo**
This update follows an update of diagonal QN operators in LinearOperators.jl.

See https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/pull/316

### CODE REVIEW

**Comment by dpo** [comment]
@tmigot Is there a reason for the `SpectralGradientModel` to exist separately from `DiagonalQNModel`? It’s just a special case.

**Comment by tmigot** [comment]
There was no specific reason, and I think your PR clarifies it. The changes look for me, and running locally the tests are passing. So, we just need a new (breaking) release of LinearOperators.jl after https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/pull/316

**Comment by dpo** [comment]
I believe the AmplNLReader failure should go away after this PR has been merged.

**Review by tmigot — APPROVED** [review]
LGTM, thanks!
AmplNLReader.jl fails because we didn't update to NLPModels 0.19 and 0.20 as we haven't implemented the linear API yet there. So, that's an expected failure I would say.

**Pull request merged**
