### PR TITLE
Define 5 arg hprod! for QuasiNewtonModel

### PR DESCRIPTION
**Pull request by mohamed82008**
This method is needed when using Percival with LBFGSModel.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
The breakage tests have been updated to work with forks now. Can you rebase?

**Comment by mohamed82008** [comment]
Sure

**Comment by abelsiqueira** [comment]
Thanks

**Comment by abelsiqueira** [comment]
I just realized that using `LBFGSMOdel` with `Percival` will need some work because you have to use `push!` to update the approximation.

**Comment by abelsiqueira** [comment]
Here's how we do it in `tron`: https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/blob/master/src/tron.jl#L138

**Comment by abelsiqueira** [comment]
But now I've been reminded that Percival calls `tron`, so maybe it's not needed?!
Well, it needs some thought on what Hessian is being approximated, and I don't remember it well enough.
But since you're testing it, let me know what you find.

**Comment by mohamed82008** [comment]
Ya Percival calls tron on the augmented Lagrangian. The Hessian being approximated is that of the augmented Lagrangian.

**Pull request merged**
