### PR TITLE
Remove `AbstractNLPModel` from the structure

### PR DESCRIPTION
**Pull request by tmigot**
This was already done in `FeasibilityFormNLS`.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
Any idea on what's up with Cirrus?

**Comment by tmigot** [comment]
> Any idea on what's up with Cirrus?

Checking the previous PRs, the error appears when we changed `master` to `main`, but not sure what to do with it.

**Comment by tmigot** [comment]
'AmplNLReader' because I actually need this PR and another one to fix it after the new 'NLPModelMeta'.

For 'JSOSolvers', there is a conflict with the Krylov.solve! function.

**Comment by abelsiqueira** [comment]
Thanks.

**Pull request merged**
